services:
  web-app:
    build: backend/
    ports:
      - "8000:8000"
    volumes:
      - ./backend/core:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=database
      - DB_NAME=db_name
      - DB_USER=db_user
      - DB_PASS=pass
    depends_on:
      - database

  database:
    image: postgres:15.8-alpine
    environment:
      - POSTGRES_DB=db_name
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=pass