# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import books_pb2 as books__pb2


class BookServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getBookById = channel.unary_unary(
                '/BookService/getBookById',
                request_serializer=books__pb2.BookRequest.SerializeToString,
                response_deserializer=books__pb2.BookResponse.FromString,
                )
        self.getAllBooks = channel.unary_unary(
                '/BookService/getAllBooks',
                request_serializer=books__pb2.EmptyRequest.SerializeToString,
                response_deserializer=books__pb2.BookListResponse.FromString,
                )


class BookServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getBookById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getAllBooks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BookServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getBookById': grpc.unary_unary_rpc_method_handler(
                    servicer.getBookById,
                    request_deserializer=books__pb2.BookRequest.FromString,
                    response_serializer=books__pb2.BookResponse.SerializeToString,
            ),
            'getAllBooks': grpc.unary_unary_rpc_method_handler(
                    servicer.getAllBooks,
                    request_deserializer=books__pb2.EmptyRequest.FromString,
                    response_serializer=books__pb2.BookListResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'BookService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BookService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getBookById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/BookService/getBookById',
            books__pb2.BookRequest.SerializeToString,
            books__pb2.BookResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getAllBooks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/BookService/getAllBooks',
            books__pb2.EmptyRequest.SerializeToString,
            books__pb2.BookListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
