# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: books.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x62ooks.proto\"\x19\n\x0b\x42ookRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"9\n\x0c\x42ookResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t\"\x0e\n\x0c\x45mptyRequest\"0\n\x10\x42ookListResponse\x12\x1c\n\x05\x62ooks\x18\x01 \x03(\x0b\x32\r.BookResponse2j\n\x0b\x42ookService\x12*\n\x0bgetBookById\x12\x0c.BookRequest\x1a\r.BookResponse\x12/\n\x0bgetAllBooks\x12\r.EmptyRequest\x1a\x11.BookListResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'books_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_BOOKREQUEST']._serialized_start=15
  _globals['_BOOKREQUEST']._serialized_end=40
  _globals['_BOOKRESPONSE']._serialized_start=42
  _globals['_BOOKRESPONSE']._serialized_end=99
  _globals['_EMPTYREQUEST']._serialized_start=101
  _globals['_EMPTYREQUEST']._serialized_end=115
  _globals['_BOOKLISTRESPONSE']._serialized_start=117
  _globals['_BOOKLISTRESPONSE']._serialized_end=165
  _globals['_BOOKSERVICE']._serialized_start=167
  _globals['_BOOKSERVICE']._serialized_end=273
# @@protoc_insertion_point(module_scope)
